"""empty message

Revision ID: b61994da2d38
Revises: f2462c7de352
Create Date: 2019-04-27 18:30:37.864958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b61994da2d38'
down_revision = 'f2462c7de352'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('superior_category', sa.VARCHAR(length=200), nullable=True),
    sa.Column('remark', sa.VARCHAR(), nullable=True),
    sa.Column('creat_time', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
