"""empty message

Revision ID: e8803c50a0d7
Revises: 
Create Date: 2019-04-29 21:06:52.176248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8803c50a0d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('damaged',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('batch', sa.Integer(), nullable=True),
    sa.Column('standard_id', sa.String(length=200), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('creat_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('check_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deposit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('batch', sa.Integer(), nullable=True),
    sa.Column('standard_id', sa.String(length=200), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('creat_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('check_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('depot_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('remark', sa.String(), nullable=True),
    sa.Column('creat_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('takeout',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('batch', sa.Integer(), nullable=True),
    sa.Column('standard_id', sa.String(length=200), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('express', sa.String(length=200), nullable=True),
    sa.Column('creat_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('check_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('contact', sa.String(length=200), nullable=True),
    sa.Column('telephone', sa.Integer(), nullable=True),
    sa.Column('remark', sa.String(), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('creat_time', sa.DateTime(), nullable=True),
    sa.Column('takeout', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['takeout'], ['takeout.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('depot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('category_id', sa.String(length=200), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('area', sa.Integer(), nullable=True),
    sa.Column('contact', sa.String(length=200), nullable=True),
    sa.Column('telephone', sa.Integer(), nullable=True),
    sa.Column('remark', sa.String(), nullable=True),
    sa.Column('creat_time', sa.DateTime(), nullable=True),
    sa.Column('deposit', sa.String(length=200), nullable=True),
    sa.Column('takeout', sa.String(length=200), nullable=True),
    sa.Column('Damaged', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['Damaged'], ['damaged.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['depot_category.id'], ),
    sa.ForeignKeyConstraint(['deposit'], ['deposit.id'], ),
    sa.ForeignKeyConstraint(['takeout'], ['takeout.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('inside_code', sa.String(length=200), nullable=True),
    sa.Column('external_code', sa.String(length=200), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('remark', sa.String(), nullable=True),
    sa.Column('creat_time', sa.DateTime(), nullable=True),
    sa.Column('deposit', sa.String(length=200), nullable=True),
    sa.Column('takeout', sa.String(length=200), nullable=True),
    sa.Column('Damaged', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['Damaged'], ['damaged.id'], ),
    sa.ForeignKeyConstraint(['deposit'], ['deposit.id'], ),
    sa.ForeignKeyConstraint(['takeout'], ['takeout.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partner',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('contact', sa.String(length=200), nullable=True),
    sa.Column('telephone', sa.Integer(), nullable=True),
    sa.Column('remark', sa.String(), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('creat_time', sa.DateTime(), nullable=True),
    sa.Column('deposit', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['deposit'], ['deposit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('remark', sa.String(), nullable=True),
    sa.Column('creat_time', sa.DateTime(), nullable=True),
    sa.Column('deposit', sa.String(length=200), nullable=True),
    sa.Column('takeout', sa.String(length=200), nullable=True),
    sa.Column('Damaged', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['Damaged'], ['damaged.id'], ),
    sa.ForeignKeyConstraint(['deposit'], ['deposit.id'], ),
    sa.ForeignKeyConstraint(['takeout'], ['takeout.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=10), nullable=True),
    sa.Column('telephone', sa.Integer(), nullable=True),
    sa.Column('password', sa.String(length=50), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('deposit', sa.String(length=200), nullable=True),
    sa.Column('takeout', sa.String(length=200), nullable=True),
    sa.Column('Damaged', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['Damaged'], ['damaged.id'], ),
    sa.ForeignKeyConstraint(['deposit'], ['deposit.id'], ),
    sa.ForeignKeyConstraint(['takeout'], ['takeout.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('department',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('superior_category', sa.String(length=200), nullable=True),
    sa.Column('creat_time', sa.DateTime(), nullable=True),
    sa.Column('user', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goods_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('remark', sa.String(), nullable=True),
    sa.Column('creat_time', sa.DateTime(), nullable=True),
    sa.Column('goods', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['goods'], ['goods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partner_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('remark', sa.String(), nullable=True),
    sa.Column('creat_time', sa.DateTime(), nullable=True),
    sa.Column('partners', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['partners'], ['partner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=10), nullable=True),
    sa.Column('remark', sa.String(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('user', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('standard',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('remark', sa.String(), nullable=True),
    sa.Column('creat_time', sa.DateTime(), nullable=True),
    sa.Column('goods', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['goods'], ['goods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('creat_time', sa.DateTime(), nullable=True),
    sa.Column('goods', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['goods'], ['goods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unit')
    op.drop_table('standard')
    op.drop_table('role')
    op.drop_table('partner_category')
    op.drop_table('goods_category')
    op.drop_table('department')
    op.drop_table('user')
    op.drop_table('type')
    op.drop_table('partner')
    op.drop_table('goods')
    op.drop_table('depot')
    op.drop_table('client')
    op.drop_table('takeout')
    op.drop_table('depot_category')
    op.drop_table('deposit')
    op.drop_table('damaged')
    # ### end Alembic commands ###
