"""empty message

Revision ID: f2462c7de352
Revises: 
Create Date: 2019-04-27 18:18:50.573483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2462c7de352'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('superior_category', sa.String(length=200), nullable=True),
    sa.Column('remark', sa.String(), nullable=True),
    sa.Column('creat_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('contact', sa.String(length=200), nullable=True),
    sa.Column('telephone', sa.Integer(), nullable=True),
    sa.Column('remark', sa.String(), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('creat_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partner',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('contact', sa.String(length=200), nullable=True),
    sa.Column('telephone', sa.Integer(), nullable=True),
    sa.Column('remark', sa.String(), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=200), nullable=True),
    sa.Column('creat_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('creat_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=10), nullable=True),
    sa.Column('telephone', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=50), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('inside_code', sa.String(length=200), nullable=True),
    sa.Column('external_code', sa.String(length=200), nullable=True),
    sa.Column('standard', sa.String(length=200), nullable=True),
    sa.Column('unit', sa.String(length=200), nullable=True),
    sa.Column('package', sa.String(length=200), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('remark', sa.String(), nullable=True),
    sa.Column('creat_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['unit'], ['unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goods')
    op.drop_table('user')
    op.drop_table('unit')
    op.drop_table('partner')
    op.drop_table('client')
    op.drop_table('category')
    # ### end Alembic commands ###
